# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trend' do
  use_frameworks!

  pod 'AlamofireImage', '~> 3.5'
  pod 'MBProgressHUD', '~> 1.0.0'

end
